### ISSUE TITLE
No permission 

### ISSUE THREAD

**Issue by zach324** [RLBot/RLBotGUI#131]
Every time I try to download Rlbot GUI it gives me an error. Windows cannot access the specified path,  device or file. You may not have the appropriate permissions. That is what the error says. Can someone please help?

**Comment by VirxEC** [comment]
Please [join our discord](https://discord.gg/zbaAKPt) so we can discuss your issue

**Comment by NicEastvillage** [comment]
@zach324  Was this issues resolved?
