### ISSUE TITLE
Latest RLBotGUI does not work on fresh install

### ISSUE THREAD

**Issue by Lunarexxy** [RLBot/RLBotGUI#147]
I downloaded RLBot from the "Download RLBot for Windows" link on rlbot.org, and installed it with the default settings. It's the first time I've ever installed it on this machine.

Upon launching it, I get an error message saying _"It looks like a recent change to RLBotGUI broke things for you, sorry! Very old versions are not able to auto-upgrade anymore, please check out our upgrade instructions to fix this."_

The upgrade instructions page says that users need to download RLBotGUI from rlbot.org, and that the new RLBotGUI uses a launcher, and not an installer, but the latest release offered here and on the website, the `.msi` file, is an installer. I uninstalled and re-installed. Didn't fix anything.

The `.exe` file fails in the same way if RLBotGUI is installed.

If RLBotGUI is _not_ installed, running the `.exe` file fails with an error message saying there's "No Python in %AppData%\Local\RLBotGUIX\Python37\python.exe"

I'm running Windows 10.

Is there something I'm missing? Is there supposed to be a launcher somewhere?

**Comment by Garrett51678** [comment]
Same here im new to coding or anything that relates to that but I saw bot 1v1 on twitch yesterday so I was wanting to try it but my launcher is saying im running an old version off of 3 fresh installs

**Comment by tarehart** [comment]
Sorry it's not working for you! Sounds like it got installed properly, except the web app portion of RLBotGUI is acting up. It works fine for me, so to further diagnose this could you please give me this info?
1. A screenshot or paste of the black console output
2. A screenshot or paste of the javascript console output for RLBotGUI (visible if you press F12)

Thanks!

**Comment by Lunarexxy** [comment]
Turns out my Javascript-blocking browser extension was stopping it from loading properly. (didn't realize the UI was just a Chrome window!)

Whitelisting localhost in the Javascript blocker fixed the issue.

Here are the console outputs anyway, in case it helps someone out in the future.
System console output: https://i.imgur.com/PiWJCko.png
Javascript console output: https://i.imgur.com/8t9NIA3.png

**Comment by tarehart** [comment]
Oh that would do it, thanks for following up! I'll make a little change to mention the javascript requirement in the error message. How about you @Garrett51678, are you still having trouble?

**Comment by Garrett51678** [comment]
Yes i'm still having problems. Sorry I was late I was eating dinner but the console is blank.
<img width="673" alt="BC1" src="https://user-images.githubusercontent.com/79063208/107895330-e4087080-6f2a-11eb-915c-03d112eacf93.PNG">
<img width="660" alt="BC2" src="https://user-images.githubusercontent.com/79063208/107895331-e4a10700-6f2a-11eb-98f8-cb93a9efef05.PNG">
<img width="658" alt="BC3" src="https://user-images.githubusercontent.com/79063208/107895332-e4a10700-6f2a-11eb-9581-96a576fd1701.PNG">
<img width="962" alt="NC1" src="https://user-images.githubusercontent.com/79063208/107895333-e5399d80-6f2a-11eb-923e-dbd13f5aad50.PNG">

**Comment by tarehart** [comment]
That's strange. Let's focus on the javascript console, could you please press F5 to refresh it? It may be missing errors that occurred before you hit F12. I would also be interested to see the 'Network' tab, maybe something failed to load there.

**Comment by Garrett51678** [comment]
I've reloaded the page and nothing changed...where was the network tab you wanted me to check out?

**Comment by tarehart** [comment]
This one here 
![image](https://user-images.githubusercontent.com/575644/107898194-029d4600-6ef0-11eb-847b-312af0db68fe.png)

**Comment by Garrett51678** [comment]
It looks blank also.
<img width="960" alt="NW1" src="https://user-images.githubusercontent.com/79063208/107898525-d60b1d80-6f33-11eb-979a-7cbdfcebf488.PNG">

**Comment by tarehart** [comment]
What if you press F5 while the network tab is still open?

**Comment by Garrett51678** [comment]
More items loaded but the dhf stadum is red and there might be more errors in there.
<img width="469" alt="NW2" src="https://user-images.githubusercontent.com/79063208/107898687-4c0f8480-6f34-11eb-85a6-a7bb923542fb.PNG">

**Comment by tarehart** [comment]
Anything else red? Is the console still empty?

**Comment by Garrett51678** [comment]
I refreshed the page and clicked on the red error sign at the top right and this popped up and also the console is empty besides this error sign
<img width="469" alt="NW2" src="https://user-images.githubusercontent.com/79063208/107899060-33539e80-6f35-11eb-90f4-1cb062aa95a7.PNG">
<img width="644" alt="S1" src="https://user-images.githubusercontent.com/79063208/107899061-33539e80-6f35-11eb-839c-a0c765057d90.PNG">

**Comment by tarehart** [comment]
Thanks for sharing the info. I'm not sure what the problem is, I'll think about it.

**Comment by Garrett51678** [comment]
okay thank you I will attempt to figure this out also I will check back here every once in a while.
