### ISSUE TITLE
Redesign of Player Types card

### ISSUE THREAD

**Issue by IamEld3st** [RLBot/RLBotGUI#155]
After few conversations on Discord, me and @Darxeal came up with an update that fixes the cluttered Player Type card. I will try to explain what is the plan.

* Move scripts to a separate modal
* Add gamemode filtering
* Add gamemode subfilters
* Change behaviour of Human tile
* Rename card to Bots

Here is some examples of how the card could look with the changes:
![image](https://user-images.githubusercontent.com/2871817/113463761-17925200-9428-11eb-8dde-6bb7134a4377.png)
![image](https://user-images.githubusercontent.com/2871817/113463852-b8810d00-9428-11eb-9ae9-61edb4638d92.png)

We also discussed specifics on how should some of these changes work.

---

### Card content changes:
`All` should work the same way as the card worked, except not include scripts.
`Standard` should include only bots that indicate they support standard in their config files.
`Extra Modes` should only show bots made for specific gamemode based on what subfilter is selected.
`Other` should show other bots, like memebots or script specific bots.

The `Bots for scripts` subfilter should show bots compatible with one or more of the currently selected scripts. The card should switch to `Bots for scripts` subfilter automatically if user exits the `Scripts` modal and atleast one script is enabled. If there is no script enabled and user switches to this subfilter, it should show info/warning message in place where the bot tiles would normally be.

All bots that dont have any category flags in their config will be shown in `All` gamemode only, as we don't know what that bot supports.

---

### Human tile behaviour changes:
There should only exist one `Human` tile. It could on first run of gui be automatically put in Blue team. If `Human` tile is removed from a team it should be put back into the bot list. It should also be shown in all gamemodes and subfilters.

---

#### Optional quality of life changes:
Remove `Recommendations` button as it adds clutter and it looks like nobody is using it. Gamemodes/Subfilters should give a similar benefit.
Add scrolling feature as mentioned in #84.

**Comment by NicEastvillage** [comment]
Sounds like a solid solution. I support this suggestion.

One thing that is not mentioned, is wether the the bots are hidden or is just grayed out when selecting a filter/subfilter where they do not belong. I would like them to be hidden personally.

I would also like to hide the subfilter buttons if the ALL filter is selected to reduce the amount of clutter.

**Comment by IamEld3st** [comment]
I forgot to mention those two things but we discussed it as well.

Bot tiles will be hidden either when you are searching or selected a subfilter.

And naturally the `All` gamemodes shouldn't have any subfilters. The only "filter" there will be the search.

**Comment by Darxeal** [comment]
> One thing that is not mentioned, is wether the the bots are hidden or is just grayed out when selecting a filter/subfilter where they do not belong. I would like them to be hidden personally.

It wasn't mentioned but yes, hiding the bots is our intention. Think of this feature more as tabs, than a filter.

> I would also like to hide the subfilter buttons if the ALL filter is selected to reduce the amount of clutter.

Yep, that's also what we intended. I personally would also put the actual filter/search field in the place where the subfilters are. The search field only makes sense when there is a lot of bots, and with this system that should hopefully be only in the "all" tab.

**Comment by L0laapk3** [comment]
I think the recommendations button should stay or at least be its own issue :)
