### ISSUE TITLE
Support for Legendary

### ISSUE THREAD

**Issue by raycekar** [RLBot/RLBotGUI#193]
Personally not a fan of having to start the epic game launcher to play Rocket League. This is an enhancement request to support Legendary along side the Steam and Epic launchers.

https://github.com/derrod/legendary

**Comment by tsdogs** [comment]
I second this, as I haven't been able to run it on Linux (the bot starts by RL won't load correctly)

**Comment by raycekar** [comment]
Found a work around and the RL servers were down.  I got it to work by opening RLbot GUI and starting a match, of course nothing happens as i dont have epic installed, but opening a cmd, i can launch rocket league with legendary in offline mode.  From here, looks like RLbot GUI detects RL opened up and works as normal :)

**Comment by Snivine** [comment]
I would like this as well, this could be a way to support Linux as you could use Heroic to launch the game

**Comment by VirxEC** [comment]
Support has been added in upcoming versions of RLBot v5
