### ISSUE TITLE
File "<string>", line 1, <module>  ModuleNotFoundError: No module named ' rlbot_gui '

### ISSUE THREAD

**Issue by TLRplayz** [RLBot/RLBotGUI#196]
Please help this is what it says
Checking for connection to pypi.org. . . 
Connected - Installing / upgrading RLBot components . . . 
C : \Users\tyler\ AppData\Local\RLBotGUIX\Python37\python.exe : no module named pip
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Launching RLBotGUIX!
Traceback (most recent call last) :
    File "<string>", line 1, <module>  ModuleNotFoundError: No module named ' rlbot_gui '

**Comment by redd-rl** [comment]
i gave you the solution to this in the rlbot discord. you didn't attempt to use it.

**Comment by TLRplayz** [comment]
I did it didn't work I followed the 1first one made it better but didn't sove the problem. The second one didn't do anything. And the third one need authorization to download.

**Comment by redd-rl** [comment]
Then provide said authorization, or just restart your pc and try the solution again.

**Comment by JoshyDevRL** [comment]
Well, just ask again in the discord ;9

**Comment by TLRplayz** [comment]
It needs authorization to download on my phone and says not found when I type in the link on my pc

**Comment by TLRplayz** [comment]
The page not found
