### ISSUE TITLE
installer doesn't open -Search for app in the store?

### ISSUE THREAD

**Issue by TimurMou** [RLBot/RLBotGUI#202]
whenever I run the rlbotgui installer (.exe or .msi), it tells me to search for an app in the store and doesn't let me run it no matter what I try to do, I've tried to run other installers (example: Hamachi VPN) and they have worked fine
<img width="510" alt="image" src="https://user-images.githubusercontent.com/108480896/210173076-4eac77cc-1f70-4d62-8ba8-7e86a0a3de6d.png">
any ideas or recommendations on what I should do?

**Comment by VirxEC** [comment]
Reinstall RLBot, you shouldn't have to download anything from the MS Store
