### ISSUE TITLE
 ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Mja141213** [RLBot/RLBotGUI#207]
i tried to setup the program and it keeps showing me this error, i deleted everything and uninstalled the python and rlbot but it keeps showing this error
![لقطة الشاشة 2023-03-03 013452](https://user-images.githubusercontent.com/126866339/222685099-b0dd5bef-a21c-44de-b7e5-29ceb4d22d11.png)

**Comment by Anthonydt16** [comment]
j'ai le même soucis

**Comment by LuisFCave** [comment]
I had this problem.To solve it you just have to download Visual C++ in microsoft website.
https://learn.microsoft.com/pt-br/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by VirxEC** [comment]
Reinstalling RLBot from our website will fix this issue
