### ISSUE TITLE
[Dumb Question] Does RLBotGui auto updates itself ? Also, does it fetch bots new version ?

### ISSUE THREAD

**Issue by marcelfalliere** [RLBot/RLBotGUI#211]
Hello,

This may seem like a dumb question, but I haven't found the answer anywhere. I don't see a version number on RLBOTGui, and don't see a version number for a specific bot (let's say Nexto).

So my question is : if I installed RLBOTGUI 6 month ago, am I playing the version of Nexto from 6 month ago ? Does it auto update ?

Thank you in advance for clarifying this. ☮️

**Comment by Darxeal** [comment]
Hi,
RLBotGUI does auto-update itself.
Bots are not updated automatically, but when there is an update, you are prompted to download it when you open RLBotGUI.
You can read "patch notes" of bots here: https://github.com/RLBot/RLBotPack/commits/master
Nexto was not updated in a long time, so you are probably still playing the same version.

**Comment by marcelfalliere** [comment]
Thank you very much
