### ISSUE TITLE
RLBot alunching in my browser instead of as a exe on my desktop.

### ISSUE THREAD

**Issue by Zoruso** [RLBot/RLBotGUI#214]
I don't know how to fix this but someone please help as It is really annoying that it opens up in my browser instead of a exe
![image_2023-07-06_040157709](https://github.com/RLBot/RLBotGUI/assets/103226169/f42ade84-6e3a-4f37-87b5-535cfab7c3e8)
![image_2023-07-06_040214202](https://github.com/RLBot/RLBotGUI/assets/103226169/12d675d2-317a-4b63-b2ee-96523b910aa6)

**Comment by VirxEC** [comment]
This is intended behavior.
