### ISSUE TITLE
Fix ping command in installer

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBotGUI#219]
We use the ping command in a batch script to check if the user has an internet connection before installing/upgrading RLBot. Some users do not have ping installed on their machines, so RLBot fails to run for them.

Replace the ping command in the batch script with a Python script or tiny executable to check for an internet connection and install/upgrade RLBot.

https://github.com/RLBot/RLBotGUI/blob/ccd4506a58b89b99d5ea500ae7ff319f2bc9a8da/alternative-install/RLBotGUI.bat#L38

**Comment by TheBlocks** [comment]
Closing as this has been fixed: https://github.com/RLBot/gui-installer/blob/ab3e3f1b9e9a7102acb93657a5671446f2b685d2/RLBotGUIX%20main%20exe/RLBotGUIX.bat#L24
