### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by fhcirf111** [RLBot/RLBotGUI#227]
I use RLBot for a month already i think and now when i tried to open it Windows Defender said that this is a virus. I don't remember what was it (it already got deleted) but i think it was some type of a "Trojan.(something that starts with a v)". Now im scared to download it again. Did someone hack RLBot and made a virus update? Or how did this happen? Does anyone else have this issue?

**Comment by fhcirf111** [comment]
Oh it is here again. It says "Trojan:Win32/Vigorf.A"

**Comment by CTAG07** [comment]
This has been happening since the most recent update, rlbot is still safe, windows just doesn't like something that it's using and says it's a virus

**Comment by fhcirf111** [comment]
Thank you. I wonder when the new update will come out because im still scared to download it lol.
