### ISSUE TITLE
When will the list of parts (bodies, decals, etc) get updated

### ISSUE THREAD

**Issue by KageGamingDE** [RLBot/RLBotGUI#228]
When will we get an update which adds all the new content from the last 2 months to rlbot?

**Comment by ddthj** [comment]
Might have to wait for the next release of RLBot, unless someone is bored and decides to update the item lists.

**Comment by NeonMoshieKage** [comment]
I'm going to ask it on my new account again, when will the list of parts get updated? or how do i do it myself
