### ISSUE TITLE
Fallback to default browser when chrome is not installed fails.

### ISSUE THREAD

**Issue by EnderWigginDA** [RLBot/RLBotGUI#233]
I don't have chrome installed. Think I used RLbot GUI 2 days ago.
TypeError: start() got an unexpected keyword argument 'callback'

![image](https://github.com/user-attachments/assets/7585f9fb-d8e6-4a59-b4b6-1aefc4601dee)

**Comment by swz-git** [comment]
Fix from https://github.com/RLBot/RLBotGUI/pull/234 is now live, restart rlbot and it'll update itself.
