### ISSUE TITLE
Don't allow GUI to start match when there aren't any bots or humans on either team.

### ISSUE THREAD

**Issue by ViliamVadocz** [RLBot/RLBotGUI#40]
The GUI got stuck after I accidentally started a match without any bots or humans. I had to restart the GUI and game to fix the issue.

Gray out Start Match when there aren't any players on each team.
![image](https://user-images.githubusercontent.com/26529068/60756622-c9a4ac00-9fff-11e9-96a9-b681306b67ef.png)

**Comment by tarehart** [comment]
Thanks for reporting! I'll probably change the framework so it doesn't get stuck. Can gray it out too though.
