### ISSUE TITLE
Dom's first experience with this GUI

### ISSUE THREAD

**Issue by DomNomNom** [RLBot/RLBotGUI#6]
First of all, great job! GUI looks slick and I was able to setup a match with Python bots from the RLBotPack quickly.

Here's a list of things that could be improved, in the order of importance (to me):

The RLBotPack disappears between launches. (note: I've used a custom install directory)
I need to redownload every time even though the RLBotPack folder is within the RLBotGUI folder.

Problems relating to Java. As a first time user, I expect that I can follow the installation instructions of RLBotGUI and run every bot in RLBotPack. I can not run AirBud. I get `'java' is not recognized as an internal or external command, operable program or batch file.` in the console window that's launched alongside the GUI when I launch.
I'm no java expert but there's different versions of Java and different bots might require different ones? 
If we detect that java is missing, the GUI should give a pointer to where to install it. Maybe only do this once a user tries to use a Java bot by adding it into a team. Maybe the provider of the bot should set a `special_instalation_instructions` as part of the details which we show on first import?
Also, does Java need/have an equivalent of `virtualenv`?

Currently I need to close both the `cmd` window and the GUI window. 
I want to only close one window, the other window should close with it.
This PR should help: https://github.com/tarehart/RLBotGUI/pull/1

I can't pin RLBotGUI to the windows taskbar. I think using a shortcut like this would work:
Target: `%windir%\system32\cmd.exe /C start /B "" "%CD%\install-and-run.bat"`
Start In: `C:\Users\RLBot\Documents\RLBotGUI`  <-- RLBotGUI install folder
This also gives the command prompt window a different task bar icon to the default shell which is nice when I want to also have a shell open to develop my bot.

Note: I can't seem to create issues on tareharts fork. Not sure why not

Left-clicking on a bot puts it on the blue team. Right-clicking on it should put it on the orange team. (note: you can still do you electron inspect devtools on it by using ctrl-shift-c)

The introduction video does not cover that it'll take 1-2 minutes to download dependencies.
Note: you can ship the dependencies you want as wheel files and then install them in your virtualenv
https://medium.com/@amimahloof/how-to-package-a-python-project-with-all-of-its-dependencies-for-offline-install-7eb240b27418

The introduction video does not sufficiently explain what the console window is for. Something short like this would suffice I think "You can see what it is doing behind the scenes here. If a bot has problems, it'll show up here." 
Optional, or as a separate video: Teach the viewer basic bug triage: where/how to report errors. How to copy in `cmd` is not obvious.

Btw, big thanks for using `virtualenv`, keeps things clean! :D

**Comment by skyborgff** [comment]
I'll hijack this to add one further suggestion. We are able to drag and drop into a team but not out of it. we should be able to drag to the bot list to make it leave the team

**Comment by NicEastvillage** [comment]
I see there's some feedback on the setup video, so I will just add this: Mention that page-up and page-down toggles rendering.
