### ISSUE TITLE
New solution to get item ids for the appearance editor

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBotGUI#72]
Our current solution relies on fetching a json file from the AlphaConsole github: https://github.com/RLBot/RLBotGUI/blob/master/rlbot_gui/gui/appearance-editor.vue#L162

https://raw.githubusercontent.com/AlphaConsole/AlphaConsoleElectron/public/items.json

Unfortunately this file is not getting updated anymore since AlphaConsole is deprecated.

We need an alternative. Bakkes has helpfully pointed out that the BakkesMod console command `dumpitems` will create a csv file with all the items. Suggested solution:
- Make a script to convert the csv file into a json file with the same format that AlphaConsole used
- Do the dump, run the script, and add the json file inside RLBotGUI
- Somebody would need to redo the dump every season

**Comment by robbai** [comment]
Alternatively skip the conversion to JSON and implement a CSV parser for the GUI
