### ISSUE TITLE
StoryMode should be able to support hivemind bots

### ISSUE THREAD

**Issue by azeemba** [RLBot/RLBotGUI#91]
Right now StoryMode doesn't know to how to identify a hivemind bot and to do the appropriate set up for them

**Comment by ViliamVadocz** [comment]
What problems are you experiencing? It should be have the same setup as normal bots.

**Comment by tarehart** [comment]
With hive mind bots, generally you can just throw them on the same team together and they'll figure it out from there. If you put somebody against 3 bumblebees, I expect it will just work.

**Comment by azeemba** [comment]
I think I just saw the [`bootstrap_python_hivemind`](https://github.com/RLBot/RLBotGUI/blob/master/rlbot_gui/bot_management/bot_creation.py#L110) defined and I figured I needed to investigate what bootstrapping is needed. Looking at the code, I might have misunderstood what's going on.

**Comment by azeemba** [comment]
I just tested this and there is some step missing. 3 bumblebees got added to the match but they weren't moving.

**Comment by tarehart** [comment]
Any errors in the console? Do three bumblebees work for you when started in the standard RLBotGUI view? They're a bit particular about needing python 3.7 64 bit

**Comment by azeemba** [comment]
They do work through RLBotGUI. 
When I do it through Story Mode, there are no errors but no logs from the hivemind. Perhaps I am missing something from the match_config or the player config.

**Comment by tarehart** [comment]
I tried it myself and I'm having the same problem, I'll investigate.

**Comment by azeemba** [comment]
Fixed in #95
